import type { AdminReviewTaskDetail } from "@pollycar/contracts";

export const syntheticTasks: readonly AdminReviewTaskDetail[] = [
  {
    taskId: "task-001",
    applicationId: "application-001",
    accountReference: "合成账户 · 001",
    status: "available",
    submittedAt: "2026-07-11T08:00:00.000Z",
    vehicleCategory: "舒适型轿车",
    insuranceExpiryStatus: "incomplete",
    authorizationEvidenceStatus: "complete",
    attachmentValidationStatus: "valid",
    taskVersion: 1,
    vehicleReviewVersion: 3,
    synthetic: true,
  },
  {
    taskId: "task-002",
    applicationId: "application-002",
    accountReference: "合成账户 · 002",
    status: "available",
    submittedAt: "2026-07-11T08:18:00.000Z",
    vehicleCategory: "新能源轿车",
    insuranceExpiryStatus: "complete",
    authorizationEvidenceStatus: "incomplete",
    attachmentValidationStatus: "invalid",
    taskVersion: 1,
    vehicleReviewVersion: 1,
    synthetic: true,
  },
  {
    taskId: "task-003",
    applicationId: "application-003",
    accountReference: "合成账户 · 003",
    status: "available",
    submittedAt: "2026-07-11T08:32:00.000Z",
    vehicleCategory: "紧凑型轿车",
    insuranceExpiryStatus: "complete",
    authorizationEvidenceStatus: "complete",
    attachmentValidationStatus: "valid",
    taskVersion: 1,
    vehicleReviewVersion: 1,
    synthetic: true,
  },
];
