import type { ApiErrorResponse } from "@pollycar/contracts";

type ErrorDefinition = Readonly<{
  status: number;
  message: string;
  retryable: boolean;
}>;

const definitions: Readonly<Record<string, ErrorDefinition>> = {
  VALIDATION_FAILED: { status: 400, message: "请求格式不正确", retryable: false },
  AVATAR_UPLOAD_INVALID: { status: 400, message: "头像文件无效，请重新选择", retryable: false },
  AVATAR_FILE_TOO_LARGE: { status: 413, message: "头像文件过大，请选择较小的图片", retryable: false },
  AVATAR_IMAGE_INVALID: { status: 422, message: "无法读取这张图片，请重新选择", retryable: false },
  AVATAR_DIMENSIONS_INVALID: { status: 422, message: "头像尺寸不符合要求，请重新选择", retryable: false },
  AVATAR_NOT_FOUND: { status: 404, message: "头像不存在或已被替换", retryable: false },
  AUTHENTICATION_REQUIRED: { status: 401, message: "需要内部沙箱身份", retryable: false },
  AUTHORIZATION_DENIED: { status: 403, message: "当前身份无权执行此操作", retryable: false },
  ADMIN_INVITATION_INVALID: { status: 404, message: "邀请不存在或已完成激活", retryable: false },
  ADMIN_INVITATION_EXPIRED: { status: 410, message: "邀请已过期", retryable: false },
  ADMIN_CREDENTIAL_INVALID: { status: 401, message: "工作邮箱或密码不正确", retryable: false },
  ADMIN_ACCOUNT_LOCKED: { status: 423, message: "登录失败次数过多，请稍后重试", retryable: true },
  ADMIN_LOGIN_CHALLENGE_EXPIRED: { status: 410, message: "登录验证已过期，请重新登录", retryable: false },
  ADMIN_MFA_INVALID: { status: 401, message: "动态验证码不正确", retryable: true },
  ADMIN_WORK_IDENTITY_SELECTION_EXPIRED: { status: 410, message: "工作身份选择已过期，请重新登录", retryable: false },
  ADMIN_WORK_IDENTITY_FORBIDDEN: { status: 403, message: "当前账号不能使用该工作身份", retryable: false },
  ADMIN_AUTH_MFA_FRESHNESS_REQUIRED: { status: 401, message: "切换工作身份前需要重新完成安全验证", retryable: false },
  ADMIN_PAGINATION_INVALID: { status: 422, message: "分页参数不正确", retryable: false },
  ADMIN_CURSOR_INVALID: { status: 422, message: "分页位置无效，请从第一页重新查询", retryable: false },
  ADMIN_CURSOR_SCOPE_MISMATCH: { status: 403, message: "分页位置与当前查询或组织范围不一致", retryable: false },
  ADMIN_OPERATIONS_TASK_NOT_FOUND: { status: 404, message: "未找到该工作任务", retryable: false },
  ADMIN_OPERATIONS_TASK_ACTION_INVALID: { status: 409, message: "当前任务状态不允许执行该操作", retryable: false },
  ADMIN_EXECUTIVE_IMPLEMENTATION_NOT_APPROVED: { status: 403, message: "阶段五实现尚未获准", retryable: false },
  ADMIN_EXECUTIVE_SCOPE_FORBIDDEN: { status: 403, message: "当前组织范围无权读取该高层聚合", retryable: false },
  ADMIN_EXECUTIVE_FILTER_SCOPE_INVALID: { status: 403, message: "筛选条件不能扩大服务端组织范围", retryable: false },
  ADMIN_EXECUTIVE_METRIC_STALE: { status: 409, message: "指标已超过新鲜度目标", retryable: true },
  ADMIN_EXECUTIVE_UNCLOSED_DATA_RESTRICTED: { status: 409, message: "未关账数据不能用于正式报告或导出", retryable: false },
  ADMIN_EXECUTIVE_DRILLDOWN_FORBIDDEN: { status: 403, message: "该钻取维度不在允许范围内", retryable: false },
  ADMIN_EXECUTIVE_SENSITIVE_DETAIL_FORBIDDEN: { status: 403, message: "驾驶舱不得返回严格敏感明细", retryable: false },
  ADMIN_EXECUTIVE_OPERATION_FORBIDDEN: { status: 403, message: "高层驾驶舱不能执行领域业务命令", retryable: false },
  ADMIN_EXECUTIVE_EXPORT_PURPOSE_REQUIRED: { status: 422, message: "导出申请必须说明用途", retryable: false },
  ADMIN_EXECUTIVE_EXPORT_REVIEWER_CONFLICT: { status: 409, message: "申请人不能审批自己的导出", retryable: false },
  ADMIN_EXECUTIVE_EXPORT_FORBIDDEN: { status: 403, message: "当前导出状态或身份不允许此操作", retryable: false },
  ADMIN_EXECUTIVE_EXPORT_EXPIRED: { status: 410, message: "导出下载授权已过期", retryable: false },
  ADMIN_EXECUTIVE_DECISION_OPINION_FORBIDDEN: { status: 403, message: "当前身份或待决事项不允许记录高层意见", retryable: false },
  ADMIN_EXECUTIVE_EXACT_AMOUNT_FORBIDDEN: { status: 403, message: "当前身份无权读取精确聚合金额", retryable: false },
  ADMIN_EXECUTIVE_EXPORT_DOMAIN_MIXED_FORBIDDEN: { status: 422, message: "单次导出不能混合多个职责域", retryable: false },
  ADMIN_EXECUTIVE_RESOURCE_NOT_FOUND: { status: 404, message: "未找到该驾驶舱记录或当前组织无权查看", retryable: false },
  ADMIN_AUDIT_RESOURCE_NOT_FOUND: { status: 404, message: "未找到该审计资源或当前组织无权查看", retryable: false },
  ADMIN_AUDIT_OPERATION_FORBIDDEN: { status: 403, message: "当前角色或调查状态不允许执行该操作", retryable: false },
  ADMIN_DATA_REPORT_NOT_FOUND: { status: 404, message: "未找到该数据报表", retryable: false },
  ADMIN_DATA_REPORT_OPERATION_FORBIDDEN: { status: 403, message: "当前角色无权刷新该数据报表", retryable: false },
  SESSION_EXPIRED: { status: 401, message: "内部会话已过期，请重新连接", retryable: false },
  SESSION_REVOKED: { status: 401, message: "内部会话已撤销，请重新连接", retryable: false },
  SESSION_IDENTITY_NOT_AVAILABLE: { status: 403, message: "当前账户尚不能使用该身份", retryable: false },
  SESSION_IDENTITY_MISMATCH: { status: 403, message: "请先切换到对应身份后再执行此操作", retryable: false },
  TRIP_RATING_NOT_ALLOWED: { status: 409, message: "当前行程不能评价", retryable: false },
  CHAT_NOT_FOUND: { status: 404, message: "行程会话不存在", retryable: false },
  DATA_RETENTION_ACTIVE: { status: 409, message: "数据仍在必要保留期内", retryable: false },
  DATA_DELETION_BLOCKED_BY_HOLD: { status: 409, message: "安全证据保留期间暂不能删除", retryable: false },
  VEHICLE_REVIEW_FORBIDDEN: { status: 403, message: "无权访问该车辆审核申请", retryable: false },
  VEHICLE_REVIEW_NOT_FOUND: { status: 404, message: "车辆审核申请不存在", retryable: false },
  ADMIN_TASK_NOT_FOUND: { status: 404, message: "审核任务不存在", retryable: false },
  IDEMPOTENT_RESULT_NOT_FOUND: { status: 404, message: "尚未找到原命令结果", retryable: true },
  ADMIN_TASK_ALREADY_CLAIMED: { status: 409, message: "该任务已由其他审核员认领", retryable: true },
  ADMIN_TASK_OWNERSHIP_LOST: { status: 409, message: "当前任务所有权已失效", retryable: true },
  VERSION_CONFLICT: { status: 409, message: "任务版本已变化", retryable: true },
  STORAGE_CONCURRENT_MODIFICATION: { status: 409, message: "审核状态已变化，请刷新后重试", retryable: true },
  CONFLICT_IDEMPOTENCY_KEY_REUSED: { status: 409, message: "请求标识已被用于其他操作", retryable: false },
  ADMIN_DECISION_REASON_REQUIRED: { status: 422, message: "需要选择原因并预览文案", retryable: false },
  VEHICLE_REVIEW_INCOMPLETE: { status: 422, message: "车辆资料尚未完整", retryable: false },
  VEHICLE_REVIEW_INVALID_STATE: { status: 422, message: "当前审核状态不允许此操作", retryable: false },
  REAL_DATA_FORBIDDEN: { status: 422, message: "内部沙箱只允许合成数据", retryable: false },
  ELIGIBILITY_INVALID_TRANSITION: { status: 422, message: "当前资格状态不允许此操作", retryable: false },
  ELIGIBILITY_INVALID_STATE: { status: 422, message: "当前资格状态不可用于免费试验", retryable: false },
  ELIGIBILITY_ACTIVATION_DAYS_EXCEEDED: { status: 422, message: "90 日内启用天数已达到上限", retryable: false },
  ELIGIBILITY_PAID_PATH_FROZEN: { status: 422, message: "付费资格路径仍处于冻结状态", retryable: false },
  TRIP_NOT_FOUND: { status: 404, message: "合成行程不存在", retryable: false },
  TRIP_FORBIDDEN: { status: 403, message: "当前账户无权操作该行程", retryable: false },
  TRIP_SELF_ACCEPT_FORBIDDEN: { status: 403, message: "车主不能接受自己创建的行程", retryable: false },
  TRIP_PASSENGER_CAPACITY_EXCEEDED: { status: 422, message: "乘车人数超过当前车辆单次人数上限", retryable: false },
  TRIP_PAYMENT_REQUIRED: { status: 422, message: "必须先完成零金额支付前置", retryable: false },
  TRIP_INVALID_STATE: { status: 422, message: "当前行程状态不允许此操作", retryable: false },
  TRIP_ALREADY_ASSIGNED: { status: 409, message: "该行程已由其他车主接受", retryable: false },
  DRIVER_ALREADY_BUSY: { status: 409, message: "你已有正在进行的即时行程", retryable: false },
  TRIP_OFFER_EXPIRED: { status: 409, message: "接单邀请已过期或撤回", retryable: false },
  DRIVER_LOCATION_STALE: { status: 409, message: "车主位置已过期，请重新定位上线", retryable: true },
  TRIP_ACCEPT_RESULT_UNKNOWN: { status: 503, message: "接单结果尚未确认，请使用原请求标识重试", retryable: true },
  TRIP_PICKUP_TIME_INVALID: { status: 422, message: "预约时间无效", retryable: false },
  TRIP_PICKUP_TIME_IN_PAST: { status: 422, message: "选择的上车时间已经过去", retryable: false },
  TRIP_PICKUP_TIME_TOO_SOON: { status: 422, message: "预约时间距离现在太近，请选择尽快出发", retryable: false },
  TRIP_PICKUP_TIME_TOO_FAR: { status: 422, message: "最多可预约未来三天", retryable: false },
  TRIP_PICKUP_TIME_UNAVAILABLE: { status: 422, message: "该时间暂不可预约", retryable: true },
  TRIP_SCHEDULE_CONFLICT: { status: 409, message: "该时间与车主已有行程冲突", retryable: false },
  TRIP_SCHEDULE_CHANGED: { status: 409, message: "预约信息已更新，请确认最新时间", retryable: true },
  TRIP_SCHEDULE_RESULT_UNKNOWN: { status: 503, message: "预约结果尚未确认，请勿重复提交", retryable: true },
  TRIP_SCHEDULE_NOT_READY: { status: 422, message: "尚未进入预约履约准备时间", retryable: false },
  DRIVER_NOT_ONLINE: { status: 422, message: "车主上线后才能接单", retryable: false },
  DRIVER_AVAILABILITY_BUSY: { status: 422, message: "履约期间不能切换接单状态", retryable: false },
  TRIP_CANCELLATION_WINDOW_EXPIRED: { status: 422, message: "接单后三分钟取消窗口已结束", retryable: false },
  TRIP_CANCELLATION_REASON_REQUIRED: { status: 422, message: "已超过三分钟自由取消窗口，请选择取消原因", retryable: false },
  GOODWILL_CANCELLATION_DISABLED: { status: 503, message: "善意取消额度当前不可用", retryable: true },
  GOODWILL_CANCELLATION_TRIP_STATE_EXCEEDED: { status: 422, message: "当前履约阶段不能使用善意取消额度", retryable: false },
  GOODWILL_CANCELLATION_HOURS24_EXCEEDED: { status: 422, message: "近 24 小时善意取消额度已用完", retryable: false },
  GOODWILL_CANCELLATION_DAYS7_EXCEEDED: { status: 422, message: "近 7 日善意取消额度已用完", retryable: false },
  GOODWILL_CANCELLATION_DAYS30_EXCEEDED: { status: 422, message: "近 30 日善意取消额度已用完", retryable: false },
  TRIP_CANCELLATION_REASON_INVALID: { status: 422, message: "取消原因不受支持", retryable: false },
  TRIP_CANCELLATION_NOTE_TOO_LONG: { status: 422, message: "取消补充说明过长", retryable: false },
  TRIP_BOARDING_CODE_INVALID: { status: 422, message: "上车确认码不正确", retryable: false },
  TRIP_BOARDING_CODE_EXPIRED: { status: 422, message: "上车确认码已过期", retryable: false },
  TRIP_COMPLETION_INTENT_INVALID: { status: 422, message: "完成确认已失效", retryable: false },
  TRIP_COMPLETION_INTENT_EXPIRED: { status: 422, message: "滑动完成确认已超时", retryable: false },
  TRIP_COMPLETION_INTENT_CONSUMED: { status: 409, message: "滑动完成确认已使用", retryable: false },
  REAL_FINANCIAL_DATA_FORBIDDEN: { status: 422, message: "真实绑卡和提现能力保持关闭", retryable: false },
  TRIP_TIMEOUT_NOT_REACHED: { status: 422, message: "尚未达到合成超时边界", retryable: false },
  QUOTA_24H_EXCEEDED: { status: 422, message: "24 小时参与额度已用完", retryable: false },
  QUOTA_7D_EXCEEDED: { status: 422, message: "7 日参与额度已用完", retryable: false },
  QUOTA_30D_EXCEEDED: { status: 422, message: "30 日参与额度已用完", retryable: false },
  QUOTA_DRIVER_INELIGIBLE: { status: 403, message: "当前车主资格不可接单", retryable: false },
  CHAT_NOT_OPEN: { status: 422, message: "临时对话尚未开放", retryable: false },
  CHAT_FROZEN: { status: 403, message: "临时对话已因安全举报冻结", retryable: false },
  CHAT_MESSAGE_INVALID: { status: 400, message: "行程消息为空或超过长度限制", retryable: false },
  SAFETY_CASE_ALREADY_OPEN: { status: 409, message: "该行程已有未结安全案件", retryable: false },
  SAFETY_CASE_NOT_FOUND: { status: 404, message: "安全案件不存在", retryable: false },
  SAFETY_APPEAL_FORBIDDEN: { status: 403, message: "只有被举报方可以提交申诉", retryable: false },
  SAFETY_INVALID_STATE: { status: 422, message: "当前安全案件状态不允许此操作", retryable: false },
  ADULT_ELIGIBILITY_REQUIRED: { status: 403, message: "请先完成成年资格验证", retryable: false },
  ADULT_ELIGIBILITY_DOCUMENT_INCOMPLETE: { status: 422, message: "请补充完整的证件材料", retryable: true },
  ADULT_ELIGIBILITY_AUTHORIZATION_REQUIRED: { status: 422, message: "请先阅读说明并确认授权", retryable: false },
  ADULT_ELIGIBILITY_APPEAL_INVALID: { status: 422, message: "请补充有效的申诉说明", retryable: false },
  ADULT_ELIGIBILITY_APPEAL_NOT_FOUND: { status: 404, message: "未找到待复核的申诉", retryable: false },
  ADULT_ELIGIBILITY_VERIFICATION_NOT_FOUND: { status: 404, message: "未找到验证记录", retryable: false },
  ADULT_ELIGIBILITY_INVALID_STATE: { status: 409, message: "当前验证状态不允许此操作", retryable: false },
  REAL_IDENTITY_DATA_FORBIDDEN: { status: 403, message: "当前环境不接收真实身份材料", retryable: false },
  EXTERNAL_IDENTITY_PROVIDER_DISABLED: { status: 403, message: "当前环境未启用真实身份核验服务", retryable: false },
  REAL_BIOMETRIC_DATA_FORBIDDEN: { status: 403, message: "当前环境不接收真实人脸材料", retryable: false },
  ADMIN_LEASE_RENEWAL_TOO_EARLY: { status: 422, message: "尚未进入租约续期窗口", retryable: false },
  FEATURE_DISABLED: { status: 403, message: "该合成功能门禁当前关闭", retryable: false },
  ADMIN_OPERATOR_SCOPE_FORBIDDEN: { status: 403, message: "当前组织范围不能访问该运营主体", retryable: false },
  ADMIN_CITY_SCOPE_FORBIDDEN: { status: 403, message: "当前组织范围不能访问该城市", retryable: false },
  ADMIN_ORGANIZATION_CONTEXT_FIXED: { status: 403, message: "运营主体组织上下文不可切换", retryable: false },
  ADMIN_TEMPORARY_GRANT_REQUIRED: { status: 403, message: "该数据需要有效的临时授权", retryable: true },
  ADMIN_TEMPORARY_GRANT_TTL_EXCEEDED: { status: 422, message: "临时授权有效期超过允许上限", retryable: false },
  ADMIN_TEMPORARY_GRANT_EXPIRED: { status: 403, message: "临时授权已到期", retryable: true },
  ADMIN_SESSION_PURPOSE_CONFLICT: { status: 403, message: "当前会话目的不能同时承担高层查看与日常经办", retryable: false },
  ADMIN_AUDIT_IMMUTABLE: { status: 403, message: "审计记录不可修改或删除", retryable: false },
  ADMIN_MEMBERSHIP_NOT_FOUND: { status: 404, message: "未找到该成员或当前组织无权查看", retryable: false },
  ADMIN_MEMBERSHIP_OPERATION_FORBIDDEN: { status: 403, message: "当前角色只能查看成员信息", retryable: false },
  ADMIN_MEMBERSHIP_STATE_INVALID: { status: 409, message: "成员当前状态不允许执行该操作", retryable: false },
  ADMIN_MEMBERSHIP_SELF_SUSPEND_FORBIDDEN: { status: 403, message: "不能暂停当前登录成员", retryable: false },
  ADMIN_OPERATOR_RESOURCE_NOT_FOUND: { status: 404, message: "未找到指定的运营主体管理资源", retryable: false },
  ADMIN_FLEET_RESOURCE_NOT_FOUND: { status: 404, message: "未找到指定的车主或车辆", retryable: false },
  ADMIN_REVIEW_TASK_NOT_FOUND: { status: 404, message: "未找到指定的车辆审核任务", retryable: false },
  ADMIN_OPERATOR_ACTION_INVALID: { status: 409, message: "当前运营主体状态或角色不允许执行该操作", retryable: false },
  ADMIN_OPERATOR_INVALID_TRANSITION: { status: 409, message: "运营主体当前状态不允许此转换", retryable: false },
  ADMIN_OPERATOR_OPEN_ONBOARDING_EXISTS: { status: 409, message: "该运营主体已存在未关闭的入驻案件", retryable: false },
  ADMIN_OPERATOR_CHECKLIST_INCOMPLETE: { status: 409, message: "入驻检查项尚未全部完成", retryable: false },
  ADMIN_OPERATOR_ACTIVE_CAPABILITY_REQUIRED: { status: 409, message: "运营主体至少需要保留一项有效城市能力", retryable: false },
  ADMIN_OPERATOR_WILDCARD_SCOPE_FORBIDDEN: { status: 403, message: "运营主体人员不得使用通配组织范围", retryable: false },
  ADMIN_OPERATOR_OPEN_MIGRATION_EXISTS: { status: 409, message: "该车主已存在未关闭的主运营关系迁移案件", retryable: false },
  ADMIN_OPERATOR_TARGET_CAPABILITY_MISSING: { status: 409, message: "目标运营主体缺少所需城市能力", retryable: false },
  ADMIN_OPERATOR_MIGRATION_BLOCKED: { status: 409, message: "主运营关系迁移仍存在阻断项", retryable: true },
  ADMIN_OPERATOR_EFFECTIVE_TIME_INVALID: { status: 422, message: "迁移生效时间不符合受控窗口要求", retryable: false },
  ADMIN_OPERATOR_MIGRATION_ALREADY_EFFECTIVE: { status: 409, message: "主运营关系迁移已经生效", retryable: false },
  ADMIN_OPERATOR_EXIT_BLOCKED: { status: 409, message: "运营主体仍有未清理事项，不能退出", retryable: true },
  ADMIN_OPERATOR_REENTRY_REQUIRES_NEW_PROFILE: { status: 409, message: "已退出主体重新入驻必须创建新档案", retryable: false },
  ADMIN_TRIP_SCOPE_FORBIDDEN: { status: 403, message: "当前组织范围不能访问该行程", retryable: false },
  ADMIN_TRIP_NOT_FOUND: { status: 404, message: "未找到合成行程", retryable: false },
  ADMIN_TRIP_TASK_NOT_FOUND: { status: 404, message: "未找到行程运营任务", retryable: false },
  ADMIN_TRIP_OPERATION_ACTION_INVALID: { status: 409, message: "当前任务状态或角色不允许执行该行程操作", retryable: false },
  ADMIN_SUPPORT_CASE_NOT_FOUND: { status: 404, message: "未找到客服案件", retryable: false },
  ADMIN_SAFETY_CASE_NOT_FOUND: { status: 404, message: "未找到安全案件", retryable: false },
  ADMIN_SAFETY_RESTORATION_BLOCKED: { status: 409, message: "安全恢复仍存在阻断项", retryable: false },
  ADMIN_CASE_ACTION_INVALID: { status: 409, message: "当前案件状态不允许执行该操作", retryable: false },
  ADMIN_EVIDENCE_GRANT_NOT_FOUND: { status: 404, message: "未找到证据访问授权", retryable: false },
  ADMIN_EVIDENCE_FIELD_NOT_GRANTED: { status: 403, message: "该字段不在证据授权范围内", retryable: false },
  ADMIN_EVIDENCE_GRANT_EXPIRED: { status: 410, message: "证据访问授权已过期", retryable: false },
  ADMIN_EVIDENCE_DUAL_APPROVAL_REQUIRED: { status: 403, message: "该证据字段需要双人批准", retryable: false },
  ADMIN_EVIDENCE_GRANT_INACTIVE: { status: 409, message: "证据访问授权当前不可用", retryable: false },
  ADMIN_EVIDENCE_TTL_EXCEEDED: { status: 422, message: "证据访问时限必须在三十分钟内", retryable: false },
  ADMIN_RECOVERY_TASK_NOT_FOUND: { status: 404, message: "未找到未知结果恢复任务", retryable: false },
  ADMIN_COMMAND_RECOVERY_IN_PROGRESS: { status: 409, message: "未知结果恢复任务正在处理中", retryable: true },
  ADMIN_RECOVERY_BUSINESS_DECISION_FORBIDDEN: { status: 403, message: "技术运维不能替代业务角色作决定", retryable: false },
  ADMIN_FINANCE_IMPLEMENTATION_NOT_APPROVED: { status: 403, message: "资金运营代码实现尚未批准", retryable: false },
  ADMIN_FINANCE_SCOPE_FORBIDDEN: { status: 403, message: "无权访问该主体资金记录", retryable: false },
  ADMIN_FINANCE_OPERATOR_PAYMENT_DATA_FORBIDDEN: { status: 403, message: "无权访问其他运营主体付款数据", retryable: false },
  ADMIN_FINANCE_AMOUNT_EDIT_FORBIDDEN: { status: 403, message: "资金金额只能由服务端计算", retryable: false },
  ADMIN_FINANCE_BALANCE_MUTATION_FORBIDDEN: { status: 403, message: "后台不得修改余额投影", retryable: false },
  ADMIN_FINANCE_DIRECT_LEDGER_POST_FORBIDDEN: { status: 403, message: "后台不得直接创建账本分录", retryable: false },
  ADMIN_FINANCE_ALLOCATION_IMMUTABLE: { status: 403, message: "固定分配结果不可编辑", retryable: false },
  ADMIN_FINANCE_REVIEWER_CONFLICT: { status: 409, message: "经办人与复核人必须不同", retryable: false },
  ADMIN_FINANCE_SETTLEMENT_BLOCKED: { status: 422, message: "运营主体清算被资金硬门阻断", retryable: true },
  ADMIN_FINANCE_PAYOUT_NOT_T_PLUS_ONE: { status: 422, message: "车主付款只能处理前一业务日分配", retryable: false },
  ADMIN_FINANCE_PAYOUT_BLOCKED: { status: 422, message: "车主付款被资金硬门阻断", retryable: true },
  DRIVER_EARLY_SETTLEMENT_DISABLED: { status: 403, message: "车主提前结算能力尚未启用", retryable: false },
  ADMIN_FINANCE_REFUND_INELIGIBLE: { status: 422, message: "退款缺少合格原支付或责任结论", retryable: false },
  ADMIN_FINANCE_PROVIDER_RESULT_REQUIRED: { status: 422, message: "必须等待支付机构权威结果", retryable: true },
  ADMIN_FINANCE_REVERSAL_INVALID: { status: 422, message: "完整冲正必须引用原交易并保持等额反向唯一", retryable: false },
  ADMIN_FINANCE_RECONCILIATION_BLOCKED: { status: 422, message: "对账差异尚未满足解决条件", retryable: true },
  ADMIN_FINANCE_RESOLUTION_EVIDENCE_REQUIRED: { status: 422, message: "差异解决必须引用证据", retryable: false },
  ADMIN_FINANCE_DAY_CLOSE_BLOCKED: { status: 422, message: "账务日仍存在未关闭运行或差异", retryable: true },
  ADMIN_FINANCE_LEDGER_SCOPE_FORBIDDEN: { status: 403, message: "无权查询该账本交易", retryable: false },
  ADMIN_FINANCE_EXPORT_FORBIDDEN: { status: 403, message: "未获得受控资金导出授权", retryable: false },
  ADMIN_FINANCE_UNKNOWN_RESULT_IN_PROGRESS: { status: 409, message: "未知结果恢复处理中，禁止创建替代命令", retryable: true },
  ADMIN_FINANCE_RECOVERY_BUSINESS_DECISION_FORBIDDEN: { status: 403, message: "技术运维不能替代财务作业务决定", retryable: false },
  ADMIN_FINANCE_RESOURCE_NOT_FOUND: { status: 404, message: "未找到该财务记录或当前组织无权查看", retryable: false },
  ADMIN_FINANCE_ACTION_INVALID: { status: 422, message: "当前财务记录状态或角色不允许执行该操作", retryable: false },
  ADMIN_RESOURCE_VERSION_CONFLICT: { status: 409, message: "资源版本已变化，请刷新后重试", retryable: true },
  SERVICE_UNAVAILABLE: { status: 503, message: "内部沙箱服务暂不可用", retryable: true },
  INTERNAL_UNEXPECTED_ERROR: { status: 500, message: "内部服务发生错误", retryable: true },
  PHONE_NUMBER_INVALID: { status: 422, message: "请输入有效手机号", retryable: false },
  PHONE_AUTH_CONSENT_REQUIRED: { status: 422, message: "请先阅读并同意相关协议", retryable: false },
  PHONE_CODE_RATE_LIMITED: { status: 429, message: "请求过于频繁，请稍后再试", retryable: true },
  PHONE_CODE_DELIVERY_UNKNOWN: { status: 503, message: "验证码发送结果暂未确认，请稍后查看", retryable: true },
  PHONE_CODE_INVALID: { status: 422, message: "验证码不正确", retryable: true },
  PHONE_CODE_EXPIRED: { status: 410, message: "验证码已过期，请重新获取", retryable: true },
  PHONE_CODE_LOCKED: { status: 423, message: "错误次数过多，请重新获取验证码", retryable: true },
  PHONE_CODE_REPLAYED: { status: 409, message: "验证码已使用，请重新获取", retryable: true },
  REAL_PHONE_DATA_FORBIDDEN: { status: 403, message: "当前环境不接收真实手机号", retryable: false },
  REFRESH_TOKEN_REPLAYED: { status: 401, message: "会话已失效，请重新登录", retryable: false },
  REFRESH_SESSION_EXPIRED: { status: 401, message: "登录已过期，请重新登录", retryable: false },
  MAP_COORDINATE_SYSTEM_REQUIRED: { status: 422, message: "位置坐标缺少坐标系", retryable: false },
  MAP_COORDINATE_INVALID: { status: 422, message: "位置坐标无效", retryable: false },
  MAP_COORDINATE_PRECISION_EXCEEDED: { status: 422, message: "位置坐标精度超过允许范围", retryable: false },
  MAP_COORDINATE_TRANSFORM_UNAVAILABLE: { status: 422, message: "当前环境无法转换该坐标系", retryable: false },
  MAP_SEARCH_INVALID: { status: 422, message: "请输入至少两个字的地点名称", retryable: false },
  MAP_SEARCH_RATE_LIMITED: { status: 429, message: "地点搜索过于频繁，请稍后再试", retryable: true },
  MAP_REVERSE_GEOCODE_INVALID: { status: 422, message: "地图选点参数无效", retryable: false },
  MAP_ROUTE_INVALID: { status: 422, message: "路线规划参数无效", retryable: false },
  MAP_PROVIDER_TIMEOUT: { status: 504, message: "地图服务响应超时，请稍后重试", retryable: true },
  MAP_PROVIDER_UNAVAILABLE: { status: 503, message: "地图服务暂不可用，可继续手动填写地点", retryable: true },
  MAP_QUOTA_DEGRADED: { status: 503, message: "地图搜索服务暂时受限，可使用常用或最近地点", retryable: true },
  VEHICLE_LOCATION_FORBIDDEN: { status: 403, message: "无权读取或更新该车辆位置", retryable: false },
  VEHICLE_LOCATION_ACCURACY_INVALID: { status: 422, message: "车辆位置精度无效", retryable: false },
  VEHICLE_LOCATION_TOO_FREQUENT: { status: 429, message: "车辆位置更新过于频繁", retryable: true },
  VEHICLE_LOCATION_SEQUENCE_INVALID: { status: 409, message: "车辆位置序号已过期", retryable: false },
  VEHICLE_LOCATION_TIMESTAMP_INVALID: { status: 422, message: "车辆位置时间戳无效", retryable: false },
  VEHICLE_LOCATION_STREAM_STOPPED: { status: 409, message: "行程已结束，车辆位置上传已停止", retryable: false },
  VEHICLE_LOCATION_TRIP_MISMATCH: { status: 422, message: "车辆位置与行程不匹配", retryable: false },
  VEHICLE_LOCATION_STAGE_INVALID: { status: 422, message: "车辆位置阶段无效", retryable: false },
  AMAP_WEB_SERVICE_DISABLED: { status: 403, message: "高德 Web 服务能力未启用", retryable: false },
  AMAP_WEB_SERVICE_KEY_MISSING: { status: 503, message: "地图供应商密钥未配置", retryable: false },
  AMAP_RESPONSE_UNSUPPORTED: { status: 503, message: "地图供应商响应尚未获准解析", retryable: false },
};

export function mapError(error: unknown, correlationId: string): Readonly<{
  status: number;
  body: ApiErrorResponse;
}> {
  const code =
    error instanceof Error && definitions[error.message]
      ? error.message
      : "INTERNAL_UNEXPECTED_ERROR";
  const definition = definitions[code] ?? definitions.INTERNAL_UNEXPECTED_ERROR!;
  return {
    status: definition.status,
    body: {
      error: {
        code,
        message: definition.message,
        retryable: definition.retryable,
        correlationId,
      },
    },
  };
}
